#!/usr/bin/env python3

import itertools
import time
import subprocess

from test_token import validate_token

for attempt in itertools.count(1):
	try:
		token = input('Enter token')
	except EOFError:
		break

	assert validate_token(token)
	with open('token', 'w') as f:
		f.write(token.strip())

	subprocess.run(['git', 'commit', '-am', f'sample #{attempt}'], check=True)
	subprocess.run(['git', 'push'], check=True)
	t0 = time.perf_counter()

	while not validate_token(token):
		time.sleep(0.1)

	t1 = time.perf_counter()

	with open('samples', 'a') as f:
		f.write(f'{t1 - t0}\n')
