#!/usr/bin/env python3

import time
import subprocess

from test_token import validate_token

with open('token') as f:
	token = f.read().strip()

assert validate_token(token)
subprocess.run('git push'.split(), check=True)
t0 = time.perf_counter()
while not validate_token(token):
	time.sleep(0.1)
t1 = time.perf_counter()
print(t1 - t0)
